# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/om/C++/LevelEditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/om/C++/LevelEditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/om/C++/LevelEditor/CMakeFiles /Users/om/C++/LevelEditor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/om/C++/LevelEditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

deps/imgui/backends/imgui_impl_sdl2.o: deps/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : deps/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
deps/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : deps/imgui/backends/imgui_impl_sdl2.cpp.o

deps/imgui/backends/imgui_impl_sdl2.i: deps/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : deps/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
deps/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : deps/imgui/backends/imgui_impl_sdl2.cpp.i

deps/imgui/backends/imgui_impl_sdl2.s: deps/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : deps/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
deps/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : deps/imgui/backends/imgui_impl_sdl2.cpp.s

deps/imgui/backends/imgui_impl_sdlrenderer2.o: deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.o

# target to build an object file
deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.o

deps/imgui/backends/imgui_impl_sdlrenderer2.i: deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.i

# target to preprocess a source file
deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.i

deps/imgui/backends/imgui_impl_sdlrenderer2.s: deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.s

# target to generate assembly for a file
deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : deps/imgui/backends/imgui_impl_sdlrenderer2.cpp.s

deps/imgui/imgui.o: deps/imgui/imgui.cpp.o
.PHONY : deps/imgui/imgui.o

# target to build an object file
deps/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui.cpp.o
.PHONY : deps/imgui/imgui.cpp.o

deps/imgui/imgui.i: deps/imgui/imgui.cpp.i
.PHONY : deps/imgui/imgui.i

# target to preprocess a source file
deps/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui.cpp.i
.PHONY : deps/imgui/imgui.cpp.i

deps/imgui/imgui.s: deps/imgui/imgui.cpp.s
.PHONY : deps/imgui/imgui.s

# target to generate assembly for a file
deps/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui.cpp.s
.PHONY : deps/imgui/imgui.cpp.s

deps/imgui/imgui_demo.o: deps/imgui/imgui_demo.cpp.o
.PHONY : deps/imgui/imgui_demo.o

# target to build an object file
deps/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_demo.cpp.o
.PHONY : deps/imgui/imgui_demo.cpp.o

deps/imgui/imgui_demo.i: deps/imgui/imgui_demo.cpp.i
.PHONY : deps/imgui/imgui_demo.i

# target to preprocess a source file
deps/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_demo.cpp.i
.PHONY : deps/imgui/imgui_demo.cpp.i

deps/imgui/imgui_demo.s: deps/imgui/imgui_demo.cpp.s
.PHONY : deps/imgui/imgui_demo.s

# target to generate assembly for a file
deps/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_demo.cpp.s
.PHONY : deps/imgui/imgui_demo.cpp.s

deps/imgui/imgui_draw.o: deps/imgui/imgui_draw.cpp.o
.PHONY : deps/imgui/imgui_draw.o

# target to build an object file
deps/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_draw.cpp.o
.PHONY : deps/imgui/imgui_draw.cpp.o

deps/imgui/imgui_draw.i: deps/imgui/imgui_draw.cpp.i
.PHONY : deps/imgui/imgui_draw.i

# target to preprocess a source file
deps/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_draw.cpp.i
.PHONY : deps/imgui/imgui_draw.cpp.i

deps/imgui/imgui_draw.s: deps/imgui/imgui_draw.cpp.s
.PHONY : deps/imgui/imgui_draw.s

# target to generate assembly for a file
deps/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_draw.cpp.s
.PHONY : deps/imgui/imgui_draw.cpp.s

deps/imgui/imgui_tables.o: deps/imgui/imgui_tables.cpp.o
.PHONY : deps/imgui/imgui_tables.o

# target to build an object file
deps/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_tables.cpp.o
.PHONY : deps/imgui/imgui_tables.cpp.o

deps/imgui/imgui_tables.i: deps/imgui/imgui_tables.cpp.i
.PHONY : deps/imgui/imgui_tables.i

# target to preprocess a source file
deps/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_tables.cpp.i
.PHONY : deps/imgui/imgui_tables.cpp.i

deps/imgui/imgui_tables.s: deps/imgui/imgui_tables.cpp.s
.PHONY : deps/imgui/imgui_tables.s

# target to generate assembly for a file
deps/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_tables.cpp.s
.PHONY : deps/imgui/imgui_tables.cpp.s

deps/imgui/imgui_widgets.o: deps/imgui/imgui_widgets.cpp.o
.PHONY : deps/imgui/imgui_widgets.o

# target to build an object file
deps/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_widgets.cpp.o
.PHONY : deps/imgui/imgui_widgets.cpp.o

deps/imgui/imgui_widgets.i: deps/imgui/imgui_widgets.cpp.i
.PHONY : deps/imgui/imgui_widgets.i

# target to preprocess a source file
deps/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_widgets.cpp.i
.PHONY : deps/imgui/imgui_widgets.cpp.i

deps/imgui/imgui_widgets.s: deps/imgui/imgui_widgets.cpp.s
.PHONY : deps/imgui/imgui_widgets.s

# target to generate assembly for a file
deps/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/deps/imgui/imgui_widgets.cpp.s
.PHONY : deps/imgui/imgui_widgets.cpp.s

src/codeGenerator.o: src/codeGenerator.cpp.o
.PHONY : src/codeGenerator.o

# target to build an object file
src/codeGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/codeGenerator.cpp.o
.PHONY : src/codeGenerator.cpp.o

src/codeGenerator.i: src/codeGenerator.cpp.i
.PHONY : src/codeGenerator.i

# target to preprocess a source file
src/codeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/codeGenerator.cpp.i
.PHONY : src/codeGenerator.cpp.i

src/codeGenerator.s: src/codeGenerator.cpp.s
.PHONY : src/codeGenerator.s

# target to generate assembly for a file
src/codeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/codeGenerator.cpp.s
.PHONY : src/codeGenerator.cpp.s

src/editor.o: src/editor.cpp.o
.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i
.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s
.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/level.o: src/level.cpp.o
.PHONY : src/level.o

# target to build an object file
src/level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/level.cpp.o
.PHONY : src/level.cpp.o

src/level.i: src/level.cpp.i
.PHONY : src/level.i

# target to preprocess a source file
src/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/level.cpp.i
.PHONY : src/level.cpp.i

src/level.s: src/level.cpp.s
.PHONY : src/level.s

# target to generate assembly for a file
src/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/level.cpp.s
.PHONY : src/level.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... editor"
	@echo "... deps/imgui/backends/imgui_impl_sdl2.o"
	@echo "... deps/imgui/backends/imgui_impl_sdl2.i"
	@echo "... deps/imgui/backends/imgui_impl_sdl2.s"
	@echo "... deps/imgui/backends/imgui_impl_sdlrenderer2.o"
	@echo "... deps/imgui/backends/imgui_impl_sdlrenderer2.i"
	@echo "... deps/imgui/backends/imgui_impl_sdlrenderer2.s"
	@echo "... deps/imgui/imgui.o"
	@echo "... deps/imgui/imgui.i"
	@echo "... deps/imgui/imgui.s"
	@echo "... deps/imgui/imgui_demo.o"
	@echo "... deps/imgui/imgui_demo.i"
	@echo "... deps/imgui/imgui_demo.s"
	@echo "... deps/imgui/imgui_draw.o"
	@echo "... deps/imgui/imgui_draw.i"
	@echo "... deps/imgui/imgui_draw.s"
	@echo "... deps/imgui/imgui_tables.o"
	@echo "... deps/imgui/imgui_tables.i"
	@echo "... deps/imgui/imgui_tables.s"
	@echo "... deps/imgui/imgui_widgets.o"
	@echo "... deps/imgui/imgui_widgets.i"
	@echo "... deps/imgui/imgui_widgets.s"
	@echo "... src/codeGenerator.o"
	@echo "... src/codeGenerator.i"
	@echo "... src/codeGenerator.s"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/level.o"
	@echo "... src/level.i"
	@echo "... src/level.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

